name = "RepliBuild"
uuid = "4450f29b-7b71-45c6-8742-e7520a479938"
version = "2.0.2"
authors = ["grim <archjulialua@gmail.com>"]

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
Clang = "0.19"
JSON = "0.21, 1"
TOML = "1"
Dates = ">=1.9"
UUIDs = ">=1.9"
Pkg = ">=1.9"
Distributed = ">=1.9"
ProgressMeter = "1.11"
DataFrames = "1"
CSV = "0.10"
Statistics = ">=1.9"
InteractiveUtils = ">=1.9"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
